version: '3.2'
services:
  backend1:
      build: ./
      tty: true
      volumes:
          - .:/BE
          - /BE/node_modules

  loadbalancer:
      build: ./load-balancer
      tty: true
      links:
          - backend1
      ports:
          - '8080:8080'

volumes:
  backend:
